name: GitHub Pages and Release PDF

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Generate HTML using Sphinx
        run: |
          make html
          echo os.cs.luc.edu > build/html/CNAME

      - name: Generate LaTeX using Sphinx
        run: |
          make latex

      - name: make latexpdf via TeXLive
        uses: xu-cheng/texlive-action@v3
        with:
          scheme: full
          run: |
            apk add --no-cache make
            make -C build/latex

      - name: Publish HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/html

      - name: Publish PDF to GitHub Releases
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/latex/OperatingSystems.pdf
